version: "3.7"

services:
  postgres:
    image: postgres:14-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "clean_auth"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
